import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/components/Providers";
import ContentWarning from "@/components/ContentWarning";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font bg-secondary`}>
        <div className="flex flex-col min-h-screen">
          <NextAuthProvider>
            <ContentWarning />
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
            <Toaster />
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
